### ISSUE TITLE
How can I implement the vertical scroll axis for Stack / Tinder Layout?

### ISSUE THREAD

**Issue by Lavan01** [best-flutter/flutter_swiper#9]
scrollDirection -> vertical doesn't seem to work for layouts STACK and TINDER.
Please do tell how organize the Stacks vertically if the scroll direction is made vertical.

Regards
LA1 Studios

**Comment by jzoom** [comment]
We've seperated the custom layout logic into custom_layout.dart .
https://github.com/best-flutter/flutter_swiper/blob/master/lib/src/custom_layout.dart

In order to implement vertical STACK and TINDER, flow the steps below:
1、Modify `_onPanUpdate` in this file ,handle the user gesture here ,
2、Modify '_StackViewState' and '_TinderState' in 'swiper.dart',handle the parameters in vertical direction.

```
  //length of the values array below
    _animationCount = 5;

    //Array below this line, '0' index is 1.0 ,witch is the first item show in swiper.
    _startIndex = -3;
    scales = [0.7, 0.8, 0.9, 1.0, 1.0];
    offsets = [-space, -space / 3 * 2, -space / 3, 0.0, _screenWidth];
    opacity = [0.0, 0.5, 1.0, 1.0, 1.0];
```

```
 opacity = [0.0, 0.9, 0.9, 1.0, 0.0, 0.0];
    scales = [0.80, 0.80, 0.85, 0.90, 1.0, 1.0, 1.0];
    offsetsX = [0.0, 0.0, 0.0, 0.0, _screenWidth, _screenWidth];
    offsetsY = [
      0.0,
      0.0,
      -5.0,
      -10.0,
      -15.0,
      -20.0,
    ];
    rotates = [0.0, 0.0, 0.0, 0.0, 20.0, 25.0];
```
These parameters `offsetX` and `offsetY` must be supplied in vertical direction .
We'll fix this issue in the next version.

**Comment by jzoom** [comment]
![](https://github.com/jzoom/images/raw/master/stack_vertical.gif)
![](https://github.com/jzoom/images/raw/master/tinder_vertical.gif)

**Comment by Lavan01** [comment]
It's perfect now, thank you so much!

**Comment by ghozay19** [comment]
> It's perfect now, thank you so much!

hi I  have some problem, 
sometimes can scroll sometimes cannot.

but ya, it can't scroll vertical,
